pipeline:
  build:
    image: ukhomeoffice/drone-docker
    repo: docker.digital.homeoffice.gov.uk/ukhomeofficedigital/lightweight-kube-etl
    secrets: [docker_username, docker_password]
    registry: docker.digital.homeoffice.gov.uk
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push
