pipeline:
  build:
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    image: registry.hub.docker.com/plugins/docker
    repo: docker.digital.homeoffice.gov.uk/ukhomeofficedigital/lightweight-kube-etl
    secrets: [docker_username, docker_password]
    registry: docker.digital.homeoffice.gov.uk
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}
      - b${DRONE_BUILD_NUMBER}
    when:
      event: push
