pipeline:

  # build:
  #   environment:
  #     - DOCKER_HOST=tcp://172.17.0.1:2375
  #   image: registry.hub.docker.com/plugins/docker
  #   repo: docker.digital.homeoffice.gov.uk/ukhomeofficedigital/lightweight-kube-etl
  #   secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
  #   registry: docker.digital.homeoffice.gov.uk
  #   force_tag: true
  #   tags:
  #     - ${DRONE_COMMIT_SHA}
  #     - ${DRONE_COMMIT_BRANCH}
  #     - b${DRONE_BUILD_NUMBER}
  #   when:
  #     branch: master
  #     event: push
  #


  image_to_artifactory:
    image: docker:17.09.1
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_REPO=docker.digital.homeoffice.gov.uk
      - DOCKER_REPO_NAMESPACE=ukhomeofficedigital
      - DOCKER_BASEDIR=/
      - DOCKER_IMAGE=lightweight-kube-etl
    commands:
      - IMAGE="${DOCKER_REPO}${DOCKER_BASEDIR}${DOCKER_REPO_NAMESPACE}${DOCKER_BASEDIR}${DOCKER_IMAGE}"
      - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} ${DOCKER_REPO}
      - docker tag "${DOCKER_IMAGE}" "${IMAGE}:${DRONE_COMMIT_SHA}"
      - docker push "${IMAGE}:${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: push
